app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")


# 1. Industry Sector Overview: Does the chart change when radio button activated? --------

app$setInputs(showMedian = "Yes")
app$snapshot()


app$snapshot(list(output = "subsVolMedianChart"))
app$setInputs(sector = "Agriculture")
app$setInputs(showMedian = "No")
app$snapshot(list(output = "subsVolMedianChart"))
app$setInputs(region = "East of England")
app$snapshot(list(output = "subsVolMedianChart"))
app$snapshot(list(output = "median_in_sector"))
app$snapshot(list(output = "perc_in_sector"))
app$snapshot(list(output = "directionSector"))
app$setInputs(inSelect2 = "Crop and animal production")
app$snapshot(list(output = "hqSubTable"))
app$snapshot(list(output = "hqSubTable"))
app$snapshot(list(output = "hqSubTable"))
app$setInputs(inSelect = "Level 3")
app$snapshot(list(output = "hqSubTable"))
app$setInputs(inSelect2 = "Forestry and logging")
app$snapshot(list(output = "indSubChart"))
app$setInputs(inSelect = "Level 6")
app$snapshot(list(output = "indSubChart"))
app$setInputs(reset = "click")
app$setInputs(sidebar = "pathways")
app$snapshot(list(output = "treePlot"))
app$snapshot(list(output = "studinWorkChart"))
app$setInputs(sectorp = "Agriculture")
app$setInputs(sectorp = "Construction")
app$setInputs(sectorp = "Electricity & gas")
app$snapshot(list(output = "treePlot"))
app$snapshot(list(output = "treePlot"))
app$setInputs(regionp = "Yorkshire and The Humber")
app$snapshot(list(output = "treePlot"))
app$setInputs(inSelect3 = "Level 6")
app$setInputs(inSelect3 = "Level 4/5")
app$setInputs(inSelect3 = "Level 3")
app$snapshot(list(output = "treePlot"))
app$snapshot()
app$setInputs(sidebar = "overview")
app$snapshot()
